---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 伍学海.
--- DateTime: 2024/9/28 10:42
---
--参数列表
--秒杀券id
local voucherId=ARGV[1]
--用户id
local userId=ARGV[2]
--订单id
local orderId=ARGV[3]

--数据key
--库存key rua拼接用..而不用+
local stockkey='seckill:lock:'..voucherId
--订单key 存的是一种秒杀券被那些人抢了，防止有重复的人抢
local orderkey='seckill:order:'..voucherId

--判断库存是否充足 从redis中取出的是字符串先转化为数字
if(tonumber(redis.call('get',stockkey))<=0) then
    -- 库存不足返回1
    return 1;
end

--判断用户是否下单 集合set中sismember判断是否有重复的 有重复的返回1
if(redis.call('sismember',orderkey,userId)==1) then
    --该用户已经抢到过该秒杀券
    return 2;
end

--扣库存
redis.call('incrby',stockkey,-1)
--下单，将userId存在set集合中
redis.call('sadd',orderkey,userId)

--发送消息到队列 XADD Stream在rua中发，阻塞队列在java代码中发,,stream.orders事先在redis客户端创建
redis.call('xadd','stream.orders','*','voucherId',voucherId,'userId',userId,'id',orderId)
return 0

